//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerpientesYEscaleras.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SerpientesYEscaleras.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandonar.
        /// </summary>
        public static string bt_Abandonar {
            get {
                return ResourceManager.GetString("bt_Abandonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string bt_Aceptar {
            get {
                return ResourceManager.GetString("bt_Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string bt_Cancelar {
            get {
                return ResourceManager.GetString("bt_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string bt_Crear {
            get {
                return ResourceManager.GetString("bt_Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Partida.
        /// </summary>
        public static string bt_CrearPartida {
            get {
                return ResourceManager.GetString("bt_CrearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string bt_Enviar {
            get {
                return ResourceManager.GetString("bt_Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string bt_Ingresar {
            get {
                return ResourceManager.GetString("bt_Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar por Puntos.
        /// </summary>
        public static string bt_OrdenarPuntos {
            get {
                return ResourceManager.GetString("bt_OrdenarPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar por Victorias.
        /// </summary>
        public static string bt_OrdenarVictorias {
            get {
                return ResourceManager.GetString("bt_OrdenarVictorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string bt_Salir {
            get {
                return ResourceManager.GetString("bt_Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabla de Posiciones.
        /// </summary>
        public static string bt_TablaPosiciones {
            get {
                return ResourceManager.GetString("bt_TablaPosiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unirse.
        /// </summary>
        public static string bt_Unirse {
            get {
                return ResourceManager.GetString("bt_Unirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unirse a Partida.
        /// </summary>
        public static string bt_UnirsePartida {
            get {
                return ResourceManager.GetString("bt_UnirsePartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difícil.
        /// </summary>
        public static string cbi_Dificil {
            get {
                return ResourceManager.GetString("cbi_Dificil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fácil.
        /// </summary>
        public static string cbi_Facil {
            get {
                return ResourceManager.GetString("cbi_Facil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string cbi_Normal {
            get {
                return ResourceManager.GetString("cbi_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dificultad.
        /// </summary>
        public static string dgc_Dificultad {
            get {
                return ResourceManager.GetString("dgc_Dificultad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugador.
        /// </summary>
        public static string dgc_Jugador {
            get {
                return ResourceManager.GetString("dgc_Jugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensajes.
        /// </summary>
        public static string dgc_Mensajes {
            get {
                return ResourceManager.GetString("dgc_Mensajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string dgc_Nombre {
            get {
                return ResourceManager.GetString("dgc_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de verificación:.
        /// </summary>
        public static string lb_CodigoVerificacion {
            get {
                return ResourceManager.GetString("lb_CodigoVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña:.
        /// </summary>
        public static string lb_ConfirmarContrasenia {
            get {
                return ResourceManager.GetString("lb_ConfirmarContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña:.
        /// </summary>
        public static string lb_Contrasenia {
            get {
                return ResourceManager.GetString("lb_Contrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico:.
        /// </summary>
        public static string lb_CorreoElectronico {
            get {
                return ResourceManager.GetString("lb_CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dificultad:.
        /// </summary>
        public static string lb_Dificultad {
            get {
                return ResourceManager.GetString("lb_Dificultad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar de nuevo el código de verificación al usuario:.
        /// </summary>
        public static string lb_EnviarCodigo {
            get {
                return ResourceManager.GetString("lb_EnviarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperando jugadores:.
        /// </summary>
        public static string lb_Esperando {
            get {
                return ResourceManager.GetString("lb_Esperando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIN DEL JUEGO.
        /// </summary>
        public static string lb_Fin {
            get {
                return ResourceManager.GetString("lb_Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string lb_IniciarSesion {
            get {
                return ResourceManager.GetString("lb_IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        public static string lb_Nombre {
            get {
                return ResourceManager.GetString("lb_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario:.
        /// </summary>
        public static string lb_NombreUsuario {
            get {
                return ResourceManager.GetString("lb_NombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidas.
        /// </summary>
        public static string lb_Partidas {
            get {
                return ResourceManager.GetString("lb_Partidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos.
        /// </summary>
        public static string lb_Puntos {
            get {
                return ResourceManager.GetString("lb_Puntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string lb_Registrarse {
            get {
                return ResourceManager.GetString("lb_Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados.
        /// </summary>
        public static string lb_Resultados {
            get {
                return ResourceManager.GetString("lb_Resultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabla de Posiciones.
        /// </summary>
        public static string lb_TablaPosiciones {
            get {
                return ResourceManager.GetString("lb_TablaPosiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validar cuenta.
        /// </summary>
        public static string lb_ValidarCuenta {
            get {
                return ResourceManager.GetString("lb_ValidarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victorias.
        /// </summary>
        public static string lb_Victorias {
            get {
                return ResourceManager.GetString("lb_Victorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        public static string mb_Alerta {
            get {
                return ResourceManager.GetString("mb_Alerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracteres inválidos en el nombre de usuario, verifique sus datos..
        /// </summary>
        public static string mb_CaracteresInvalidos {
            get {
                return ResourceManager.GetString("mb_CaracteresInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de verificación.
        /// </summary>
        public static string mb_Codigo {
            get {
                return ResourceManager.GetString("mb_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le hemos enviado de nuevo el código de verificación al correo:  .
        /// </summary>
        public static string mb_CodigoEnviado {
            get {
                return ResourceManager.GetString("mb_CodigoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código incorrecto..
        /// </summary>
        public static string mb_CodigoIncorrecto {
            get {
                return ResourceManager.GetString("mb_CodigoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese un código..
        /// </summary>
        public static string mb_CodigoVacio {
            get {
                return ResourceManager.GetString("mb_CodigoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener 8 caracteres con una letra y un número, como mínimo..
        /// </summary>
        public static string mb_ContraseniaInvalida {
            get {
                return ResourceManager.GetString("mb_ContraseniaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No coincide la confirmación de la contraseña, verifique su contraseña..
        /// </summary>
        public static string mb_ContraseniaNoCoincide {
            get {
                return ResourceManager.GetString("mb_ContraseniaNoCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le hemos enviado un correo con el código de verificación, ingréselo para validar su cuenta..
        /// </summary>
        public static string mb_CorreoEnviado {
            get {
                return ResourceManager.GetString("mb_CorreoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico inválido, verifique sus datos..
        /// </summary>
        public static string mb_CorreoInvalido {
            get {
                return ResourceManager.GetString("mb_CorreoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este correo ya fue registrado, ingrese otro correo..
        /// </summary>
        public static string mb_CorreoOcupado {
            get {
                return ResourceManager.GetString("mb_CorreoOcupado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta cuenta aún no ha sido validada, valide su cuenta con el código de verificación..
        /// </summary>
        public static string mb_CuentaNoValidada {
            get {
                return ResourceManager.GetString("mb_CuentaNoValidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se validó la cuenta: .
        /// </summary>
        public static string mb_CuentaValidada {
            get {
                return ResourceManager.GetString("mb_CuentaValidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta cuenta ya está verificada..
        /// </summary>
        public static string mb_CuentaYaVerificada {
            get {
                return ResourceManager.GetString("mb_CuentaYaVerificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ingreso todos los campos, ingrese sus datos..
        /// </summary>
        public static string mb_DatosVacios {
            get {
                return ResourceManager.GetString("mb_DatosVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , ingréselo para validar su cuenta..
        /// </summary>
        public static string mb_IngreseCodigo {
            get {
                return ResourceManager.GetString("mb_IngreseCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el nombre de usuario al que quiere enviar el código..
        /// </summary>
        public static string mb_IngreseJugador {
            get {
                return ResourceManager.GetString("mb_IngreseJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe este jugador, verifique su nombre de usuario..
        /// </summary>
        public static string mb_JugadorInexistente {
            get {
                return ResourceManager.GetString("mb_JugadorInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listo.
        /// </summary>
        public static string mb_Listo {
            get {
                return ResourceManager.GetString("mb_Listo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este nombre de usuario ya está ocupado, ingrese otro nombre de usuario..
        /// </summary>
        public static string mb_NombreOcupado {
            get {
                return ResourceManager.GetString("mb_NombreOcupado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario o contraseña incorrectos, verifique sus datos..
        /// </summary>
        public static string mb_NombreUsuarioOContraseniaIncorrectos {
            get {
                return ResourceManager.GetString("mb_NombreUsuarioOContraseniaIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario o contraseña vacios, ingrese sus datos..
        /// </summary>
        public static string mb_NombreUsuarioOContraseniaVacios {
            get {
                return ResourceManager.GetString("mb_NombreUsuarioOContraseniaVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el nombre de la partida..
        /// </summary>
        public static string mb_NombreVacio {
            get {
                return ResourceManager.GetString("mb_NombreVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se registró correctamente..
        /// </summary>
        public static string mb_RegistroExitoso {
            get {
                return ResourceManager.GetString("mb_RegistroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código sólo puede tener números..
        /// </summary>
        public static string mb_SoloNumeros {
            get {
                return ResourceManager.GetString("mb_SoloNumeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string mi_Espaniol {
            get {
                return ResourceManager.GetString("mi_Espaniol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string mi_Idioma {
            get {
                return ResourceManager.GetString("mi_Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        public static string mi_Ingles {
            get {
                return ResourceManager.GetString("mi_Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de verifiación Serpientes Y Escaleras.
        /// </summary>
        public static string ms_Asunto {
            get {
                return ResourceManager.GetString("ms_Asunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa el siguiente código:&lt;br/&gt;.
        /// </summary>
        public static string ms_IngresaCodigo {
            get {
                return ResourceManager.GetString("ms_IngresaCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;&lt;br/&gt;No compartas este código con nadie ya que es necesario para verificar su cuenta en Serpientes y Escaleras.&lt;br/&gt;&lt;br/&gt;¡Gracias por jugar con nosotros!.
        /// </summary>
        public static string ms_Mensaje {
            get {
                return ResourceManager.GetString("ms_Mensaje", resourceCulture);
            }
        }
    }
}
