//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerpientesYEscaleras.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SerpientesYEscaleras.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandonar.
        /// </summary>
        public static string bt_Abandonar {
            get {
                return ResourceManager.GetString("bt_Abandonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string bt_Aceptar {
            get {
                return ResourceManager.GetString("bt_Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string bt_Cancelar {
            get {
                return ResourceManager.GetString("bt_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string bt_Crear {
            get {
                return ResourceManager.GetString("bt_Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Partida.
        /// </summary>
        public static string bt_CrearPartida {
            get {
                return ResourceManager.GetString("bt_CrearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string bt_Enviar {
            get {
                return ResourceManager.GetString("bt_Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string bt_Ingresar {
            get {
                return ResourceManager.GetString("bt_Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar por Puntos.
        /// </summary>
        public static string bt_OrdenarPuntos {
            get {
                return ResourceManager.GetString("bt_OrdenarPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar por Victorias.
        /// </summary>
        public static string bt_OrdenarVictorias {
            get {
                return ResourceManager.GetString("bt_OrdenarVictorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabla de Posiciones.
        /// </summary>
        public static string bt_TablaPosiciones {
            get {
                return ResourceManager.GetString("bt_TablaPosiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Términos y condiciones y Política de privacidad.
        /// </summary>
        public static string bt_TerminosYPolitica {
            get {
                return ResourceManager.GetString("bt_TerminosYPolitica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unirse.
        /// </summary>
        public static string bt_Unirse {
            get {
                return ResourceManager.GetString("bt_Unirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unirse a Partida.
        /// </summary>
        public static string bt_UnirsePartida {
            get {
                return ResourceManager.GetString("bt_UnirsePartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acepto los Términos y condiciones.
        /// </summary>
        public static string cb_TerminosCondiciones {
            get {
                return ResourceManager.GetString("cb_TerminosCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difícil.
        /// </summary>
        public static string cbi_Dificil {
            get {
                return ResourceManager.GetString("cbi_Dificil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fácil.
        /// </summary>
        public static string cbi_Facil {
            get {
                return ResourceManager.GetString("cbi_Facil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string cbi_Normal {
            get {
                return ResourceManager.GetString("cbi_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos.
        /// </summary>
        public static string dcg_Puntos {
            get {
                return ResourceManager.GetString("dcg_Puntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dificultad.
        /// </summary>
        public static string dgc_Dificultad {
            get {
                return ResourceManager.GetString("dgc_Dificultad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugador.
        /// </summary>
        public static string dgc_Jugador {
            get {
                return ResourceManager.GetString("dgc_Jugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string dgc_Nombre {
            get {
                return ResourceManager.GetString("dgc_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensajes.
        /// </summary>
        public static string gb_Mensajes {
            get {
                return ResourceManager.GetString("gb_Mensajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de verificación:.
        /// </summary>
        public static string lb_CodigoVerificacion {
            get {
                return ResourceManager.GetString("lb_CodigoVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña:.
        /// </summary>
        public static string lb_ConfirmarContrasenia {
            get {
                return ResourceManager.GetString("lb_ConfirmarContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña:.
        /// </summary>
        public static string lb_Contrasenia {
            get {
                return ResourceManager.GetString("lb_Contrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico:.
        /// </summary>
        public static string lb_CorreoElectronico {
            get {
                return ResourceManager.GetString("lb_CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dificultad:.
        /// </summary>
        public static string lb_Dificultad {
            get {
                return ResourceManager.GetString("lb_Dificultad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar de nuevo el código de verificación al usuario:.
        /// </summary>
        public static string lb_EnviarCodigo {
            get {
                return ResourceManager.GetString("lb_EnviarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperando jugadores: .
        /// </summary>
        public static string lb_Esperando {
            get {
                return ResourceManager.GetString("lb_Esperando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIN DEL JUEGO.
        /// </summary>
        public static string lb_Fin {
            get {
                return ResourceManager.GetString("lb_Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string lb_IniciarSesion {
            get {
                return ResourceManager.GetString("lb_IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        public static string lb_Nombre {
            get {
                return ResourceManager.GetString("lb_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario:.
        /// </summary>
        public static string lb_NombreUsuario {
            get {
                return ResourceManager.GetString("lb_NombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidas.
        /// </summary>
        public static string lb_Partidas {
            get {
                return ResourceManager.GetString("lb_Partidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string lb_Registrarse {
            get {
                return ResourceManager.GetString("lb_Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados.
        /// </summary>
        public static string lb_Resultados {
            get {
                return ResourceManager.GetString("lb_Resultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabla de Posiciones.
        /// </summary>
        public static string lb_TablaPosiciones {
            get {
                return ResourceManager.GetString("lb_TablaPosiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validar cuenta.
        /// </summary>
        public static string lb_ValidarCuenta {
            get {
                return ResourceManager.GetString("lb_ValidarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        public static string mb_Alerta {
            get {
                return ResourceManager.GetString("mb_Alerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cómo jugar?.
        /// </summary>
        public static string mb_Ayuda {
            get {
                return ResourceManager.GetString("mb_Ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dificultad de la partida está determinada por el número de serpientes y escaleras presentes en el tablero:
        ///Fácil: 6 escaleras y 3 serpientes.
        ///Normal: 4 escaleras y 4 serpientes.
        ///Difícil: 3 escaleras y 6 serpientes.
        ///
        ///La partida comienza cuando haya 4 jugadores.
        ///Al empezar la partida apostaras 200 puntos..
        /// </summary>
        public static string mb_AyudaDificultad {
            get {
                return ResourceManager.GetString("mb_AyudaDificultad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.- Cada jugador tiene 10 segundos para realizar su tiro.
        ///2.- Tu ficha y tu turno se encuentran en la esquina superior derecha.
        ///3..- Cuando sea tu turno, presiona el dado para tirar y se mostrará cuanto obtuviste a la derecha del dado.
        ///4.- Si un jugador no tira pierde su turno.
        ///5.- En el chat puedes mandar mensaje a los demás jugadores, además de recibir retroalimentación del juego.
        ///6.- Sólo puedes abandonar la partida cuando sea el turno de los demás jugadores. Si decides abandonar la partida perderás [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mb_AyudaPartida {
            get {
                return ResourceManager.GetString("mb_AyudaPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para unirte a una partida debes seleccionar una partida de la tabla y dar clic al botón Unirse, y te llevará a la pantalla de espera.
        ///La partida comienza cuando haya 4 jugadores.
        ///Al empezar la partida apostaras 200 puntos..
        /// </summary>
        public static string mb_AyudaUnirse {
            get {
                return ResourceManager.GetString("mb_AyudaUnirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracteres inválidos en el nombre de usuario, verifique sus datos. Sólo puede tener letras y números..
        /// </summary>
        public static string mb_CaracteresInvalidos {
            get {
                return ResourceManager.GetString("mb_CaracteresInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracteres inválidos en la contraseña, verifique sus datos. Sólo puede tener letras y números..
        /// </summary>
        public static string mb_CaracteresInvalidosContrasenia {
            get {
                return ResourceManager.GetString("mb_CaracteresInvalidosContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracteres inválidos en el mensaje, sólo puede tener letras y números..
        /// </summary>
        public static string mb_CaracteresInvalidosMensaje {
            get {
                return ResourceManager.GetString("mb_CaracteresInvalidosMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracteres inválidos en el nombre de la partida, sólo puede tener letras y números..
        /// </summary>
        public static string mb_CaracteresInvalidosPartida {
            get {
                return ResourceManager.GetString("mb_CaracteresInvalidosPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de verificación.
        /// </summary>
        public static string mb_Codigo {
            get {
                return ResourceManager.GetString("mb_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le hemos enviado de nuevo el código de verificación al correo:  .
        /// </summary>
        public static string mb_CodigoEnviado {
            get {
                return ResourceManager.GetString("mb_CodigoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código incorrecto..
        /// </summary>
        public static string mb_CodigoIncorrecto {
            get {
                return ResourceManager.GetString("mb_CodigoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese un código..
        /// </summary>
        public static string mb_CodigoVacio {
            get {
                return ResourceManager.GetString("mb_CodigoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay conexión con la base de datos, inténtelo más tarde..
        /// </summary>
        public static string mb_ConexionBD {
            get {
                return ResourceManager.GetString("mb_ConexionBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay conexión con la base de datos, por favor no cierre el juego ya que sus datos podrían no guardarse, estamos trabajando en esto, inténtelo más tarde..
        /// </summary>
        public static string mb_ConexionBD2 {
            get {
                return ResourceManager.GetString("mb_ConexionBD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay conexión con el servidor, inténtelo más tarde..
        /// </summary>
        public static string mb_ConexionServidor {
            get {
                return ResourceManager.GetString("mb_ConexionServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay conexión con el servidor, por favor no cierre el juego ya que sus datos podrían no guardarse, estamos trabajando en esto, inténtelo más tarde..
        /// </summary>
        public static string mb_ConexionServidor2 {
            get {
                return ResourceManager.GetString("mb_ConexionServidor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay conexión con el servidor, volverá al menú principal..
        /// </summary>
        public static string mb_ConexionServidor3 {
            get {
                return ResourceManager.GetString("mb_ConexionServidor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener 8 caracteres con una letra y un número, como mínimo. Sólo puede tener letras y números..
        /// </summary>
        public static string mb_ContraseniaInvalida {
            get {
                return ResourceManager.GetString("mb_ContraseniaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No coincide la confirmación de la contraseña, verifique su contraseña..
        /// </summary>
        public static string mb_ContraseniaNoCoincide {
            get {
                return ResourceManager.GetString("mb_ContraseniaNoCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le hemos enviado un correo con el código de verificación, ingréselo para validar su cuenta..
        /// </summary>
        public static string mb_CorreoEnviado {
            get {
                return ResourceManager.GetString("mb_CorreoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico inválido, verifique sus datos..
        /// </summary>
        public static string mb_CorreoInvalido {
            get {
                return ResourceManager.GetString("mb_CorreoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este correo ya fue registrado, ingrese otro correo..
        /// </summary>
        public static string mb_CorreoOcupado {
            get {
                return ResourceManager.GetString("mb_CorreoOcupado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta cuenta aún no ha sido validada, valide su cuenta con el código de verificación..
        /// </summary>
        public static string mb_CuentaNoValidada {
            get {
                return ResourceManager.GetString("mb_CuentaNoValidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se validó la cuenta: .
        /// </summary>
        public static string mb_CuentaValidada {
            get {
                return ResourceManager.GetString("mb_CuentaValidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta cuenta ya está verificada..
        /// </summary>
        public static string mb_CuentaYaVerificada {
            get {
                return ResourceManager.GetString("mb_CuentaYaVerificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ingreso todos los campos, ingrese sus datos..
        /// </summary>
        public static string mb_DatosVacios {
            get {
                return ResourceManager.GetString("mb_DatosVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pudimos enviar el código de verificación, inténtelo más tarde..
        /// </summary>
        public static string mb_EnvioFallido {
            get {
                return ResourceManager.GetString("mb_EnvioFallido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , ingréselo para validar su cuenta..
        /// </summary>
        public static string mb_IngreseCodigo {
            get {
                return ResourceManager.GetString("mb_IngreseCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el nombre de usuario al que quiere enviar el código..
        /// </summary>
        public static string mb_IngreseJugador {
            get {
                return ResourceManager.GetString("mb_IngreseJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe este jugador, verifique su nombre de usuario..
        /// </summary>
        public static string mb_JugadorInexistente {
            get {
                return ResourceManager.GetString("mb_JugadorInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listo.
        /// </summary>
        public static string mb_Listo {
            get {
                return ResourceManager.GetString("mb_Listo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este nombre de usuario ya está ocupado, ingrese otro nombre de usuario..
        /// </summary>
        public static string mb_NombreOcupado {
            get {
                return ResourceManager.GetString("mb_NombreOcupado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya creó una partida con este nombre, ingrese otro nombre..
        /// </summary>
        public static string mb_NombrePartidaOcupado {
            get {
                return ResourceManager.GetString("mb_NombrePartidaOcupado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario o contraseña incorrectos, verifique sus datos..
        /// </summary>
        public static string mb_NombreUsuarioOContraseniaIncorrectos {
            get {
                return ResourceManager.GetString("mb_NombreUsuarioOContraseniaIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario o contraseña vacios, ingrese sus datos..
        /// </summary>
        public static string mb_NombreUsuarioOContraseniaVacios {
            get {
                return ResourceManager.GetString("mb_NombreUsuarioOContraseniaVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el nombre de la partida..
        /// </summary>
        public static string mb_NombreVacio {
            get {
                return ResourceManager.GetString("mb_NombreVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes suficientes puntos para unirte o crear una partida, necesitas 200 para apostar..
        /// </summary>
        public static string mb_PuntosInsuficientes {
            get {
                return ResourceManager.GetString("mb_PuntosInsuficientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se registró correctamente..
        /// </summary>
        public static string mb_RegistroExitoso {
            get {
                return ResourceManager.GetString("mb_RegistroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporalmente no podemos registrar jugadores, inténtelo más tarde..
        /// </summary>
        public static string mb_RegistroFallido {
            get {
                return ResourceManager.GetString("mb_RegistroFallido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código sólo puede tener números..
        /// </summary>
        public static string mb_SoloNumeros {
            get {
                return ResourceManager.GetString("mb_SoloNumeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÉRMINOS DE SERVICIO
        ///Por favor, lea estas Condiciones de servicio cuidadosamente antes de acceder o utilizar nuestro juego. Al acceder o utilizar cualquier parte del juego, usted acepta que quedará vinculado por estas Condiciones de Servicio. Si usted no está de acuerdo con todos los términos y condiciones de este acuerdo, entonces usted no puede utilizar nuestro  juego. 
        ///Usted no puede usar nuestro juego para ningún propósito ilegal o no autorizado ni puede, en el uso del juego, violar cualquier ley en s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string mb_TerminosCondiciones {
            get {
                return ResourceManager.GetString("mb_TerminosCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string mi_Espaniol {
            get {
                return ResourceManager.GetString("mi_Espaniol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string mi_Idioma {
            get {
                return ResourceManager.GetString("mi_Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        public static string mi_Ingles {
            get {
                return ResourceManager.GetString("mi_Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos.
        /// </summary>
        public static string mi_Puntos {
            get {
                return ResourceManager.GetString("mi_Puntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string mi_Salir {
            get {
                return ResourceManager.GetString("mi_Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victorias.
        /// </summary>
        public static string mi_Victorias {
            get {
                return ResourceManager.GetString("mi_Victorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes aceptar los Términos y condiciones..
        /// </summary>
        public static string ms_AceptarTerminos {
            get {
                return ResourceManager.GetString("ms_AceptarTerminos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amarillo.
        /// </summary>
        public static string ms_Amarillo {
            get {
                return ResourceManager.GetString("ms_Amarillo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de verifiación Serpientes Y Escaleras.
        /// </summary>
        public static string ms_Asunto {
            get {
                return ResourceManager.GetString("ms_Asunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  está en una casilla bonus, vuelve a tirar.
        ///Bonus:
        ///1.- Vuelve al inicio
        ///2.- Divide tus casillas a la mitad
        ///3.- Retrocede 3 casillas
        ///4.- Gana 50 puntos
        ///5.- Avanza 10 casillas
        ///6.- Ve a la casilla 90.
        /// </summary>
        public static string ms_Bonus {
            get {
                return ResourceManager.GetString("ms_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL JUEGO HA COMENZADO.
        /// </summary>
        public static string ms_Comienzo {
            get {
                return ResourceManager.GetString("ms_Comienzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ganó..
        /// </summary>
        public static string ms_Gano {
            get {
                return ResourceManager.GetString("ms_Gano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa el siguiente código:&lt;br/&gt;.
        /// </summary>
        public static string ms_IngresaCodigo {
            get {
                return ResourceManager.GetString("ms_IngresaCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este jugador ya está conectado..
        /// </summary>
        public static string ms_JugadorConectado {
            get {
                return ResourceManager.GetString("ms_JugadorConectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;&lt;br/&gt;No compartas este código con nadie ya que es necesario para verificar su cuenta en Serpientes y Escaleras.&lt;br/&gt;&lt;br/&gt;¡Gracias por jugar con nosotros!.
        /// </summary>
        public static string ms_Mensaje {
            get {
                return ResourceManager.GetString("ms_Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morado.
        /// </summary>
        public static string ms_Morado {
            get {
                return ResourceManager.GetString("ms_Morado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naranja.
        /// </summary>
        public static string ms_Naranja {
            get {
                return ResourceManager.GetString("ms_Naranja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  obtuvó .
        /// </summary>
        public static string ms_Numero {
            get {
                return ResourceManager.GetString("ms_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosa.
        /// </summary>
        public static string ms_Rosa {
            get {
                return ResourceManager.GetString("ms_Rosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  salió de la partida..
        /// </summary>
        public static string ms_Salir {
            get {
                return ResourceManager.GetString("ms_Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turno.
        /// </summary>
        public static string ms_Turn {
            get {
                return ResourceManager.GetString("ms_Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es el turno de: .
        /// </summary>
        public static string ms_Turno {
            get {
                return ResourceManager.GetString("ms_Turno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  perdió su turno..
        /// </summary>
        public static string ms_TurnoPerdido {
            get {
                return ResourceManager.GetString("ms_TurnoPerdido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  se unió a la partida..
        /// </summary>
        public static string ms_Unirse {
            get {
                return ResourceManager.GetString("ms_Unirse", resourceCulture);
            }
        }
    }
}
