//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerpientesYEscaleras.ServiceSYE {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/ServiceSYE")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PuntosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short VictoriasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Puntos {
            get {
                return this.PuntosField;
            }
            set {
                if ((this.PuntosField.Equals(value) != true)) {
                    this.PuntosField = value;
                    this.RaisePropertyChanged("Puntos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Validado {
            get {
                return this.ValidadoField;
            }
            set {
                if ((this.ValidadoField.Equals(value) != true)) {
                    this.ValidadoField = value;
                    this.RaisePropertyChanged("Validado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Victorias {
            get {
                return this.VictoriasField;
            }
            set {
                if ((this.VictoriasField.Equals(value) != true)) {
                    this.VictoriasField = value;
                    this.RaisePropertyChanged("Victorias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSYE.IJugador")]
    public interface IJugador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/AddJugador", ReplyAction="http://tempuri.org/IJugador/AddJugadorResponse")]
        void AddJugador(SerpientesYEscaleras.ServiceSYE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/AddJugador", ReplyAction="http://tempuri.org/IJugador/AddJugadorResponse")]
        System.Threading.Tasks.Task AddJugadorAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/GetJugador", ReplyAction="http://tempuri.org/IJugador/GetJugadorResponse")]
        SerpientesYEscaleras.ServiceSYE.Jugador GetJugador(string nombreUsuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/GetJugador", ReplyAction="http://tempuri.org/IJugador/GetJugadorResponse")]
        System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador> GetJugadorAsync(string nombreUsuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/GetJugadoresPuntos", ReplyAction="http://tempuri.org/IJugador/GetJugadoresPuntosResponse")]
        SerpientesYEscaleras.ServiceSYE.Jugador[] GetJugadoresPuntos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/GetJugadoresPuntos", ReplyAction="http://tempuri.org/IJugador/GetJugadoresPuntosResponse")]
        System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador[]> GetJugadoresPuntosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/GetJugadoresVictorias", ReplyAction="http://tempuri.org/IJugador/GetJugadoresVictoriasResponse")]
        SerpientesYEscaleras.ServiceSYE.Jugador[] GetJugadoresVictorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/GetJugadoresVictorias", ReplyAction="http://tempuri.org/IJugador/GetJugadoresVictoriasResponse")]
        System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador[]> GetJugadoresVictoriasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJugadorChannel : SerpientesYEscaleras.ServiceSYE.IJugador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JugadorClient : System.ServiceModel.ClientBase<SerpientesYEscaleras.ServiceSYE.IJugador>, SerpientesYEscaleras.ServiceSYE.IJugador {
        
        public JugadorClient() {
        }
        
        public JugadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JugadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JugadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JugadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddJugador(SerpientesYEscaleras.ServiceSYE.Jugador jugador) {
            base.Channel.AddJugador(jugador);
        }
        
        public System.Threading.Tasks.Task AddJugadorAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador) {
            return base.Channel.AddJugadorAsync(jugador);
        }
        
        public SerpientesYEscaleras.ServiceSYE.Jugador GetJugador(string nombreUsuario, string contrasenia) {
            return base.Channel.GetJugador(nombreUsuario, contrasenia);
        }
        
        public System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador> GetJugadorAsync(string nombreUsuario, string contrasenia) {
            return base.Channel.GetJugadorAsync(nombreUsuario, contrasenia);
        }
        
        public SerpientesYEscaleras.ServiceSYE.Jugador[] GetJugadoresPuntos() {
            return base.Channel.GetJugadoresPuntos();
        }
        
        public System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador[]> GetJugadoresPuntosAsync() {
            return base.Channel.GetJugadoresPuntosAsync();
        }
        
        public SerpientesYEscaleras.ServiceSYE.Jugador[] GetJugadoresVictorias() {
            return base.Channel.GetJugadoresVictorias();
        }
        
        public System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador[]> GetJugadoresVictoriasAsync() {
            return base.Channel.GetJugadoresVictoriasAsync();
        }
    }
}
