//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerpientesYEscaleras.ServiceSYE {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/ServiceSYE")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesYEscaleras.ServiceSYE.Estadisticas EstadisticasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesYEscaleras.ServiceSYE.Turno TurnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesYEscaleras.ServiceSYE.Estadisticas Estadisticas {
            get {
                return this.EstadisticasField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadisticasField, value) != true)) {
                    this.EstadisticasField = value;
                    this.RaisePropertyChanged("Estadisticas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesYEscaleras.ServiceSYE.Turno Turno {
            get {
                return this.TurnoField;
            }
            set {
                if ((object.ReferenceEquals(this.TurnoField, value) != true)) {
                    this.TurnoField = value;
                    this.RaisePropertyChanged("Turno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estadisticas", Namespace="http://schemas.datacontract.org/2004/07/ServiceSYE")]
    [System.SerializableAttribute()]
    public partial class Estadisticas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PuntosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short VictoriasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Puntos {
            get {
                return this.PuntosField;
            }
            set {
                if ((this.PuntosField.Equals(value) != true)) {
                    this.PuntosField = value;
                    this.RaisePropertyChanged("Puntos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Victorias {
            get {
                return this.VictoriasField;
            }
            set {
                if ((this.VictoriasField.Equals(value) != true)) {
                    this.VictoriasField = value;
                    this.RaisePropertyChanged("Victorias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Turno", Namespace="http://schemas.datacontract.org/2004/07/ServiceSYE")]
    [System.SerializableAttribute()]
    public partial class Turno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesYEscaleras.ServiceSYE.Casilla CasillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroTurnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesYEscaleras.ServiceSYE.Casilla Casilla {
            get {
                return this.CasillaField;
            }
            set {
                if ((object.ReferenceEquals(this.CasillaField, value) != true)) {
                    this.CasillaField = value;
                    this.RaisePropertyChanged("Casilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroTurno {
            get {
                return this.NumeroTurnoField;
            }
            set {
                if ((this.NumeroTurnoField.Equals(value) != true)) {
                    this.NumeroTurnoField = value;
                    this.RaisePropertyChanged("NumeroTurno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Casilla", Namespace="http://schemas.datacontract.org/2004/07/ServiceSYE")]
    [System.SerializableAttribute()]
    public partial class Casilla : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BonusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PosicionXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PosicionYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Bonus {
            get {
                return this.BonusField;
            }
            set {
                if ((this.BonusField.Equals(value) != true)) {
                    this.BonusField = value;
                    this.RaisePropertyChanged("Bonus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Movimiento {
            get {
                return this.MovimientoField;
            }
            set {
                if ((this.MovimientoField.Equals(value) != true)) {
                    this.MovimientoField = value;
                    this.RaisePropertyChanged("Movimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PosicionX {
            get {
                return this.PosicionXField;
            }
            set {
                if ((this.PosicionXField.Equals(value) != true)) {
                    this.PosicionXField = value;
                    this.RaisePropertyChanged("PosicionX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PosicionY {
            get {
                return this.PosicionYField;
            }
            set {
                if ((this.PosicionYField.Equals(value) != true)) {
                    this.PosicionYField = value;
                    this.RaisePropertyChanged("PosicionY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/DataAccess")]
    [System.SerializableAttribute()]
    public partial class Jugador1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesYEscaleras.ServiceSYE.Estadisticas1 EstadisticasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesYEscaleras.ServiceSYE.Estadisticas1 Estadisticas {
            get {
                return this.EstadisticasField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadisticasField, value) != true)) {
                    this.EstadisticasField = value;
                    this.RaisePropertyChanged("Estadisticas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJugador {
            get {
                return this.IdJugadorField;
            }
            set {
                if ((this.IdJugadorField.Equals(value) != true)) {
                    this.IdJugadorField = value;
                    this.RaisePropertyChanged("IdJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseniaField, value) != true)) {
                    this.contraseniaField = value;
                    this.RaisePropertyChanged("contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoElectronicoField, value) != true)) {
                    this.correoElectronicoField = value;
                    this.RaisePropertyChanged("correoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreUsuarioField, value) != true)) {
                    this.nombreUsuarioField = value;
                    this.RaisePropertyChanged("nombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estadisticas", Namespace="http://schemas.datacontract.org/2004/07/DataAccess")]
    [System.SerializableAttribute()]
    public partial class Estadisticas1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadisticasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesYEscaleras.ServiceSYE.Jugador1 JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short puntosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short victoriasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstadisticas {
            get {
                return this.IdEstadisticasField;
            }
            set {
                if ((this.IdEstadisticasField.Equals(value) != true)) {
                    this.IdEstadisticasField = value;
                    this.RaisePropertyChanged("IdEstadisticas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesYEscaleras.ServiceSYE.Jugador1 Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short puntos {
            get {
                return this.puntosField;
            }
            set {
                if ((this.puntosField.Equals(value) != true)) {
                    this.puntosField = value;
                    this.RaisePropertyChanged("puntos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short victorias {
            get {
                return this.victoriasField;
            }
            set {
                if ((this.victoriasField.Equals(value) != true)) {
                    this.victoriasField = value;
                    this.RaisePropertyChanged("victorias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Partida", Namespace="http://schemas.datacontract.org/2004/07/ServiceSYE")]
    [System.SerializableAttribute()]
    public partial class Partida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DificultadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<object, string> JugadoresChatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<object, SerpientesYEscaleras.ServiceSYE.Jugador> JugadoresPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesYEscaleras.ServiceSYE.Tablero TableroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dificultad {
            get {
                return this.DificultadField;
            }
            set {
                if ((object.ReferenceEquals(this.DificultadField, value) != true)) {
                    this.DificultadField = value;
                    this.RaisePropertyChanged("Dificultad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<object, string> JugadoresChat {
            get {
                return this.JugadoresChatField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadoresChatField, value) != true)) {
                    this.JugadoresChatField = value;
                    this.RaisePropertyChanged("JugadoresChat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<object, SerpientesYEscaleras.ServiceSYE.Jugador> JugadoresPartida {
            get {
                return this.JugadoresPartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadoresPartidaField, value) != true)) {
                    this.JugadoresPartidaField = value;
                    this.RaisePropertyChanged("JugadoresPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesYEscaleras.ServiceSYE.Tablero Tablero {
            get {
                return this.TableroField;
            }
            set {
                if ((object.ReferenceEquals(this.TableroField, value) != true)) {
                    this.TableroField = value;
                    this.RaisePropertyChanged("Tablero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Turno {
            get {
                return this.TurnoField;
            }
            set {
                if ((this.TurnoField.Equals(value) != true)) {
                    this.TurnoField = value;
                    this.RaisePropertyChanged("Turno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tablero", Namespace="http://schemas.datacontract.org/2004/07/ServiceSYE")]
    [System.SerializableAttribute()]
    public partial class Tablero : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesYEscaleras.ServiceSYE.Casilla[] CasillasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesYEscaleras.ServiceSYE.Casilla[] Casillas {
            get {
                return this.CasillasField;
            }
            set {
                if ((object.ReferenceEquals(this.CasillasField, value) != true)) {
                    this.CasillasField = value;
                    this.RaisePropertyChanged("Casillas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSYE.IJugador")]
    public interface IJugador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/RegistrarJugador", ReplyAction="http://tempuri.org/IJugador/RegistrarJugadorResponse")]
        bool RegistrarJugador(SerpientesYEscaleras.ServiceSYE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/RegistrarJugador", ReplyAction="http://tempuri.org/IJugador/RegistrarJugadorResponse")]
        System.Threading.Tasks.Task<bool> RegistrarJugadorAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/IniciarSesion", ReplyAction="http://tempuri.org/IJugador/IniciarSesionResponse")]
        SerpientesYEscaleras.ServiceSYE.Jugador IniciarSesion(string nombreUsuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/IniciarSesion", ReplyAction="http://tempuri.org/IJugador/IniciarSesionResponse")]
        System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador> IniciarSesionAsync(string nombreUsuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/UnirseAlJuego", ReplyAction="http://tempuri.org/IJugador/UnirseAlJuegoResponse")]
        void UnirseAlJuego(SerpientesYEscaleras.ServiceSYE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/UnirseAlJuego", ReplyAction="http://tempuri.org/IJugador/UnirseAlJuegoResponse")]
        System.Threading.Tasks.Task UnirseAlJuegoAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/SalirDelJuego", ReplyAction="http://tempuri.org/IJugador/SalirDelJuegoResponse")]
        void SalirDelJuego(SerpientesYEscaleras.ServiceSYE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/SalirDelJuego", ReplyAction="http://tempuri.org/IJugador/SalirDelJuegoResponse")]
        System.Threading.Tasks.Task SalirDelJuegoAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ValidarConectado", ReplyAction="http://tempuri.org/IJugador/ValidarConectadoResponse")]
        bool ValidarConectado(SerpientesYEscaleras.ServiceSYE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ValidarConectado", ReplyAction="http://tempuri.org/IJugador/ValidarConectadoResponse")]
        System.Threading.Tasks.Task<bool> ValidarConectadoAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ObtenerJugadoresPuntos", ReplyAction="http://tempuri.org/IJugador/ObtenerJugadoresPuntosResponse")]
        SerpientesYEscaleras.ServiceSYE.Jugador[] ObtenerJugadoresPuntos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ObtenerJugadoresPuntos", ReplyAction="http://tempuri.org/IJugador/ObtenerJugadoresPuntosResponse")]
        System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador[]> ObtenerJugadoresPuntosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ObtenerJugadoresVictorias", ReplyAction="http://tempuri.org/IJugador/ObtenerJugadoresVictoriasResponse")]
        SerpientesYEscaleras.ServiceSYE.Jugador[] ObtenerJugadoresVictorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ObtenerJugadoresVictorias", ReplyAction="http://tempuri.org/IJugador/ObtenerJugadoresVictoriasResponse")]
        System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador[]> ObtenerJugadoresVictoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/EnviarCodigoACorreo", ReplyAction="http://tempuri.org/IJugador/EnviarCodigoACorreoResponse")]
        bool EnviarCodigoACorreo(SerpientesYEscaleras.ServiceSYE.Jugador jugador, string asunto, string mensajeIngresar, string mensajeFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/EnviarCodigoACorreo", ReplyAction="http://tempuri.org/IJugador/EnviarCodigoACorreoResponse")]
        System.Threading.Tasks.Task<bool> EnviarCodigoACorreoAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador, string asunto, string mensajeIngresar, string mensajeFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ObtenerJugadorPorCodigo", ReplyAction="http://tempuri.org/IJugador/ObtenerJugadorPorCodigoResponse")]
        SerpientesYEscaleras.ServiceSYE.Jugador ObtenerJugadorPorCodigo(string codigoVerificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ObtenerJugadorPorCodigo", ReplyAction="http://tempuri.org/IJugador/ObtenerJugadorPorCodigoResponse")]
        System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador> ObtenerJugadorPorCodigoAsync(string codigoVerificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ObtenerJugadorPorNombre", ReplyAction="http://tempuri.org/IJugador/ObtenerJugadorPorNombreResponse")]
        SerpientesYEscaleras.ServiceSYE.Jugador ObtenerJugadorPorNombre(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ObtenerJugadorPorNombre", ReplyAction="http://tempuri.org/IJugador/ObtenerJugadorPorNombreResponse")]
        System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador> ObtenerJugadorPorNombreAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ObtenerJugadorPorCorreo", ReplyAction="http://tempuri.org/IJugador/ObtenerJugadorPorCorreoResponse")]
        SerpientesYEscaleras.ServiceSYE.Jugador ObtenerJugadorPorCorreo(string correoElectronico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ObtenerJugadorPorCorreo", ReplyAction="http://tempuri.org/IJugador/ObtenerJugadorPorCorreoResponse")]
        System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador> ObtenerJugadorPorCorreoAsync(string correoElectronico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ValidarCuentaJugador", ReplyAction="http://tempuri.org/IJugador/ValidarCuentaJugadorResponse")]
        bool ValidarCuentaJugador(string correoElectronico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ValidarCuentaJugador", ReplyAction="http://tempuri.org/IJugador/ValidarCuentaJugadorResponse")]
        System.Threading.Tasks.Task<bool> ValidarCuentaJugadorAsync(string correoElectronico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ValidarCodigo", ReplyAction="http://tempuri.org/IJugador/ValidarCodigoResponse")]
        int ValidarCodigo(string codigoVerificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ValidarCodigo", ReplyAction="http://tempuri.org/IJugador/ValidarCodigoResponse")]
        System.Threading.Tasks.Task<int> ValidarCodigoAsync(string codigoVerificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ModificarCodigo", ReplyAction="http://tempuri.org/IJugador/ModificarCodigoResponse")]
        bool ModificarCodigo(string codigoVerificacion, string nuevoCodigoVerificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ModificarCodigo", ReplyAction="http://tempuri.org/IJugador/ModificarCodigoResponse")]
        System.Threading.Tasks.Task<bool> ModificarCodigoAsync(string codigoVerificacion, string nuevoCodigoVerificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ModificarEstadisticas", ReplyAction="http://tempuri.org/IJugador/ModificarEstadisticasResponse")]
        bool ModificarEstadisticas(string nombreUsuario, short puntos, short victorias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/ModificarEstadisticas", ReplyAction="http://tempuri.org/IJugador/ModificarEstadisticasResponse")]
        System.Threading.Tasks.Task<bool> ModificarEstadisticasAsync(string nombreUsuario, short puntos, short victorias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/CrearJugador", ReplyAction="http://tempuri.org/IJugador/CrearJugadorResponse")]
        SerpientesYEscaleras.ServiceSYE.Jugador CrearJugador(SerpientesYEscaleras.ServiceSYE.Jugador1[] jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJugador/CrearJugador", ReplyAction="http://tempuri.org/IJugador/CrearJugadorResponse")]
        System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador> CrearJugadorAsync(SerpientesYEscaleras.ServiceSYE.Jugador1[] jugador);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJugadorChannel : SerpientesYEscaleras.ServiceSYE.IJugador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JugadorClient : System.ServiceModel.ClientBase<SerpientesYEscaleras.ServiceSYE.IJugador>, SerpientesYEscaleras.ServiceSYE.IJugador {
        
        public JugadorClient() {
        }
        
        public JugadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JugadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JugadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JugadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegistrarJugador(SerpientesYEscaleras.ServiceSYE.Jugador jugador) {
            return base.Channel.RegistrarJugador(jugador);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarJugadorAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador) {
            return base.Channel.RegistrarJugadorAsync(jugador);
        }
        
        public SerpientesYEscaleras.ServiceSYE.Jugador IniciarSesion(string nombreUsuario, string contrasenia) {
            return base.Channel.IniciarSesion(nombreUsuario, contrasenia);
        }
        
        public System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador> IniciarSesionAsync(string nombreUsuario, string contrasenia) {
            return base.Channel.IniciarSesionAsync(nombreUsuario, contrasenia);
        }
        
        public void UnirseAlJuego(SerpientesYEscaleras.ServiceSYE.Jugador jugador) {
            base.Channel.UnirseAlJuego(jugador);
        }
        
        public System.Threading.Tasks.Task UnirseAlJuegoAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador) {
            return base.Channel.UnirseAlJuegoAsync(jugador);
        }
        
        public void SalirDelJuego(SerpientesYEscaleras.ServiceSYE.Jugador jugador) {
            base.Channel.SalirDelJuego(jugador);
        }
        
        public System.Threading.Tasks.Task SalirDelJuegoAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador) {
            return base.Channel.SalirDelJuegoAsync(jugador);
        }
        
        public bool ValidarConectado(SerpientesYEscaleras.ServiceSYE.Jugador jugador) {
            return base.Channel.ValidarConectado(jugador);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarConectadoAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador) {
            return base.Channel.ValidarConectadoAsync(jugador);
        }
        
        public SerpientesYEscaleras.ServiceSYE.Jugador[] ObtenerJugadoresPuntos() {
            return base.Channel.ObtenerJugadoresPuntos();
        }
        
        public System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador[]> ObtenerJugadoresPuntosAsync() {
            return base.Channel.ObtenerJugadoresPuntosAsync();
        }
        
        public SerpientesYEscaleras.ServiceSYE.Jugador[] ObtenerJugadoresVictorias() {
            return base.Channel.ObtenerJugadoresVictorias();
        }
        
        public System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador[]> ObtenerJugadoresVictoriasAsync() {
            return base.Channel.ObtenerJugadoresVictoriasAsync();
        }
        
        public bool EnviarCodigoACorreo(SerpientesYEscaleras.ServiceSYE.Jugador jugador, string asunto, string mensajeIngresar, string mensajeFinal) {
            return base.Channel.EnviarCodigoACorreo(jugador, asunto, mensajeIngresar, mensajeFinal);
        }
        
        public System.Threading.Tasks.Task<bool> EnviarCodigoACorreoAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador, string asunto, string mensajeIngresar, string mensajeFinal) {
            return base.Channel.EnviarCodigoACorreoAsync(jugador, asunto, mensajeIngresar, mensajeFinal);
        }
        
        public SerpientesYEscaleras.ServiceSYE.Jugador ObtenerJugadorPorCodigo(string codigoVerificacion) {
            return base.Channel.ObtenerJugadorPorCodigo(codigoVerificacion);
        }
        
        public System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador> ObtenerJugadorPorCodigoAsync(string codigoVerificacion) {
            return base.Channel.ObtenerJugadorPorCodigoAsync(codigoVerificacion);
        }
        
        public SerpientesYEscaleras.ServiceSYE.Jugador ObtenerJugadorPorNombre(string nombreUsuario) {
            return base.Channel.ObtenerJugadorPorNombre(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador> ObtenerJugadorPorNombreAsync(string nombreUsuario) {
            return base.Channel.ObtenerJugadorPorNombreAsync(nombreUsuario);
        }
        
        public SerpientesYEscaleras.ServiceSYE.Jugador ObtenerJugadorPorCorreo(string correoElectronico) {
            return base.Channel.ObtenerJugadorPorCorreo(correoElectronico);
        }
        
        public System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador> ObtenerJugadorPorCorreoAsync(string correoElectronico) {
            return base.Channel.ObtenerJugadorPorCorreoAsync(correoElectronico);
        }
        
        public bool ValidarCuentaJugador(string correoElectronico) {
            return base.Channel.ValidarCuentaJugador(correoElectronico);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarCuentaJugadorAsync(string correoElectronico) {
            return base.Channel.ValidarCuentaJugadorAsync(correoElectronico);
        }
        
        public int ValidarCodigo(string codigoVerificacion) {
            return base.Channel.ValidarCodigo(codigoVerificacion);
        }
        
        public System.Threading.Tasks.Task<int> ValidarCodigoAsync(string codigoVerificacion) {
            return base.Channel.ValidarCodigoAsync(codigoVerificacion);
        }
        
        public bool ModificarCodigo(string codigoVerificacion, string nuevoCodigoVerificacion) {
            return base.Channel.ModificarCodigo(codigoVerificacion, nuevoCodigoVerificacion);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarCodigoAsync(string codigoVerificacion, string nuevoCodigoVerificacion) {
            return base.Channel.ModificarCodigoAsync(codigoVerificacion, nuevoCodigoVerificacion);
        }
        
        public bool ModificarEstadisticas(string nombreUsuario, short puntos, short victorias) {
            return base.Channel.ModificarEstadisticas(nombreUsuario, puntos, victorias);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarEstadisticasAsync(string nombreUsuario, short puntos, short victorias) {
            return base.Channel.ModificarEstadisticasAsync(nombreUsuario, puntos, victorias);
        }
        
        public SerpientesYEscaleras.ServiceSYE.Jugador CrearJugador(SerpientesYEscaleras.ServiceSYE.Jugador1[] jugador) {
            return base.Channel.CrearJugador(jugador);
        }
        
        public System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Jugador> CrearJugadorAsync(SerpientesYEscaleras.ServiceSYE.Jugador1[] jugador) {
            return base.Channel.CrearJugadorAsync(jugador);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSYE.IPartida", CallbackContract=typeof(SerpientesYEscaleras.ServiceSYE.IPartidaCallback))]
    public interface IPartida {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/CrearPartida", ReplyAction="http://tempuri.org/IPartida/CrearPartidaResponse")]
        void CrearPartida(SerpientesYEscaleras.ServiceSYE.Partida partida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/CrearPartida", ReplyAction="http://tempuri.org/IPartida/CrearPartidaResponse")]
        System.Threading.Tasks.Task CrearPartidaAsync(SerpientesYEscaleras.ServiceSYE.Partida partida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/ObtenerPartidas", ReplyAction="http://tempuri.org/IPartida/ObtenerPartidasResponse")]
        SerpientesYEscaleras.ServiceSYE.Partida[] ObtenerPartidas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/ObtenerPartidas", ReplyAction="http://tempuri.org/IPartida/ObtenerPartidasResponse")]
        System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Partida[]> ObtenerPartidasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/ValidarNombrePartida", ReplyAction="http://tempuri.org/IPartida/ValidarNombrePartidaResponse")]
        bool ValidarNombrePartida(string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/ValidarNombrePartida", ReplyAction="http://tempuri.org/IPartida/ValidarNombrePartidaResponse")]
        System.Threading.Tasks.Task<bool> ValidarNombrePartidaAsync(string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/VerPartidas", ReplyAction="http://tempuri.org/IPartida/VerPartidasResponse")]
        void VerPartidas(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/VerPartidas", ReplyAction="http://tempuri.org/IPartida/VerPartidasResponse")]
        System.Threading.Tasks.Task VerPartidasAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/SalirVerPartidas", ReplyAction="http://tempuri.org/IPartida/SalirVerPartidasResponse")]
        void SalirVerPartidas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/SalirVerPartidas", ReplyAction="http://tempuri.org/IPartida/SalirVerPartidasResponse")]
        System.Threading.Tasks.Task SalirVerPartidasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/UnirsePartida", ReplyAction="http://tempuri.org/IPartida/UnirsePartidaResponse")]
        void UnirsePartida(SerpientesYEscaleras.ServiceSYE.Jugador jugador, string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/UnirsePartida", ReplyAction="http://tempuri.org/IPartida/UnirsePartidaResponse")]
        System.Threading.Tasks.Task UnirsePartidaAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador, string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/SalirPartida", ReplyAction="http://tempuri.org/IPartida/SalirPartidaResponse")]
        void SalirPartida(SerpientesYEscaleras.ServiceSYE.Jugador jugador, string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/SalirPartida", ReplyAction="http://tempuri.org/IPartida/SalirPartidaResponse")]
        System.Threading.Tasks.Task SalirPartidaAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador, string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/SalirPartidaEnJuego", ReplyAction="http://tempuri.org/IPartida/SalirPartidaEnJuegoResponse")]
        void SalirPartidaEnJuego(SerpientesYEscaleras.ServiceSYE.Jugador jugador, string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/SalirPartidaEnJuego", ReplyAction="http://tempuri.org/IPartida/SalirPartidaEnJuegoResponse")]
        System.Threading.Tasks.Task SalirPartidaEnJuegoAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador, string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/ObtenerPartida", ReplyAction="http://tempuri.org/IPartida/ObtenerPartidaResponse")]
        SerpientesYEscaleras.ServiceSYE.Partida ObtenerPartida(string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/ObtenerPartida", ReplyAction="http://tempuri.org/IPartida/ObtenerPartidaResponse")]
        System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Partida> ObtenerPartidaAsync(string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/CambiarTurno", ReplyAction="http://tempuri.org/IPartida/CambiarTurnoResponse")]
        void CambiarTurno(string nombrePartida, int casilla, int turno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/CambiarTurno", ReplyAction="http://tempuri.org/IPartida/CambiarTurnoResponse")]
        System.Threading.Tasks.Task CambiarTurnoAsync(string nombrePartida, int casilla, int turno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/MovimientoEspecial", ReplyAction="http://tempuri.org/IPartida/MovimientoEspecialResponse")]
        void MovimientoEspecial(string nombrePartida, int casilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/MovimientoEspecial", ReplyAction="http://tempuri.org/IPartida/MovimientoEspecialResponse")]
        System.Threading.Tasks.Task MovimientoEspecialAsync(string nombrePartida, int casilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/CambiarPosicionBonus", ReplyAction="http://tempuri.org/IPartida/CambiarPosicionBonusResponse")]
        void CambiarPosicionBonus(string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartida/CambiarPosicionBonus", ReplyAction="http://tempuri.org/IPartida/CambiarPosicionBonusResponse")]
        System.Threading.Tasks.Task CambiarPosicionBonusAsync(string nombrePartida);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPartidaCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPartida/ActualizarPartidas")]
        void ActualizarPartidas(SerpientesYEscaleras.ServiceSYE.Partida[] partidas);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPartida/Tirar")]
        void Tirar();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPartidaChannel : SerpientesYEscaleras.ServiceSYE.IPartida, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartidaClient : System.ServiceModel.DuplexClientBase<SerpientesYEscaleras.ServiceSYE.IPartida>, SerpientesYEscaleras.ServiceSYE.IPartida {
        
        public PartidaClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public PartidaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public PartidaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PartidaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PartidaClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void CrearPartida(SerpientesYEscaleras.ServiceSYE.Partida partida) {
            base.Channel.CrearPartida(partida);
        }
        
        public System.Threading.Tasks.Task CrearPartidaAsync(SerpientesYEscaleras.ServiceSYE.Partida partida) {
            return base.Channel.CrearPartidaAsync(partida);
        }
        
        public SerpientesYEscaleras.ServiceSYE.Partida[] ObtenerPartidas() {
            return base.Channel.ObtenerPartidas();
        }
        
        public System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Partida[]> ObtenerPartidasAsync() {
            return base.Channel.ObtenerPartidasAsync();
        }
        
        public bool ValidarNombrePartida(string nombrePartida) {
            return base.Channel.ValidarNombrePartida(nombrePartida);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarNombrePartidaAsync(string nombrePartida) {
            return base.Channel.ValidarNombrePartidaAsync(nombrePartida);
        }
        
        public void VerPartidas(string nombreUsuario) {
            base.Channel.VerPartidas(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task VerPartidasAsync(string nombreUsuario) {
            return base.Channel.VerPartidasAsync(nombreUsuario);
        }
        
        public void SalirVerPartidas() {
            base.Channel.SalirVerPartidas();
        }
        
        public System.Threading.Tasks.Task SalirVerPartidasAsync() {
            return base.Channel.SalirVerPartidasAsync();
        }
        
        public void UnirsePartida(SerpientesYEscaleras.ServiceSYE.Jugador jugador, string nombrePartida) {
            base.Channel.UnirsePartida(jugador, nombrePartida);
        }
        
        public System.Threading.Tasks.Task UnirsePartidaAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador, string nombrePartida) {
            return base.Channel.UnirsePartidaAsync(jugador, nombrePartida);
        }
        
        public void SalirPartida(SerpientesYEscaleras.ServiceSYE.Jugador jugador, string nombrePartida) {
            base.Channel.SalirPartida(jugador, nombrePartida);
        }
        
        public System.Threading.Tasks.Task SalirPartidaAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador, string nombrePartida) {
            return base.Channel.SalirPartidaAsync(jugador, nombrePartida);
        }
        
        public void SalirPartidaEnJuego(SerpientesYEscaleras.ServiceSYE.Jugador jugador, string nombrePartida) {
            base.Channel.SalirPartidaEnJuego(jugador, nombrePartida);
        }
        
        public System.Threading.Tasks.Task SalirPartidaEnJuegoAsync(SerpientesYEscaleras.ServiceSYE.Jugador jugador, string nombrePartida) {
            return base.Channel.SalirPartidaEnJuegoAsync(jugador, nombrePartida);
        }
        
        public SerpientesYEscaleras.ServiceSYE.Partida ObtenerPartida(string nombrePartida) {
            return base.Channel.ObtenerPartida(nombrePartida);
        }
        
        public System.Threading.Tasks.Task<SerpientesYEscaleras.ServiceSYE.Partida> ObtenerPartidaAsync(string nombrePartida) {
            return base.Channel.ObtenerPartidaAsync(nombrePartida);
        }
        
        public void CambiarTurno(string nombrePartida, int casilla, int turno) {
            base.Channel.CambiarTurno(nombrePartida, casilla, turno);
        }
        
        public System.Threading.Tasks.Task CambiarTurnoAsync(string nombrePartida, int casilla, int turno) {
            return base.Channel.CambiarTurnoAsync(nombrePartida, casilla, turno);
        }
        
        public void MovimientoEspecial(string nombrePartida, int casilla) {
            base.Channel.MovimientoEspecial(nombrePartida, casilla);
        }
        
        public System.Threading.Tasks.Task MovimientoEspecialAsync(string nombrePartida, int casilla) {
            return base.Channel.MovimientoEspecialAsync(nombrePartida, casilla);
        }
        
        public void CambiarPosicionBonus(string nombrePartida) {
            base.Channel.CambiarPosicionBonus(nombrePartida);
        }
        
        public System.Threading.Tasks.Task CambiarPosicionBonusAsync(string nombrePartida) {
            return base.Channel.CambiarPosicionBonusAsync(nombrePartida);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSYE.IChat", CallbackContract=typeof(SerpientesYEscaleras.ServiceSYE.IChatCallback))]
    public interface IChat {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/UnirseChat")]
        void UnirseChat(string nombreUsuario, string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/UnirseChat")]
        System.Threading.Tasks.Task UnirseChatAsync(string nombreUsuario, string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/EnviarMensaje")]
        void EnviarMensaje(string mensaje, string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/EnviarMensaje")]
        System.Threading.Tasks.Task EnviarMensajeAsync(string mensaje, string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/EnviarMensajePartida")]
        void EnviarMensajePartida(string mensaje, string nombrePartida, int tipoMensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/EnviarMensajePartida")]
        System.Threading.Tasks.Task EnviarMensajePartidaAsync(string mensaje, string nombrePartida, int tipoMensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/SalirChat")]
        void SalirChat(string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/SalirChat")]
        System.Threading.Tasks.Task SalirChatAsync(string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/SalirChatPartida")]
        void SalirChatPartida(string nombrePartida);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/SalirChatPartida")]
        System.Threading.Tasks.Task SalirChatPartidaAsync(string nombrePartida);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/RecibeMensaje")]
        void RecibeMensaje(string nombreUsuario, string mensaje, int numeroJugadores);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChat/RecibeMensajePartida")]
        void RecibeMensajePartida(string nombreUsuario, string mensaje, int tipoMensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatChannel : SerpientesYEscaleras.ServiceSYE.IChat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatClient : System.ServiceModel.DuplexClientBase<SerpientesYEscaleras.ServiceSYE.IChat>, SerpientesYEscaleras.ServiceSYE.IChat {
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void UnirseChat(string nombreUsuario, string nombrePartida) {
            base.Channel.UnirseChat(nombreUsuario, nombrePartida);
        }
        
        public System.Threading.Tasks.Task UnirseChatAsync(string nombreUsuario, string nombrePartida) {
            return base.Channel.UnirseChatAsync(nombreUsuario, nombrePartida);
        }
        
        public void EnviarMensaje(string mensaje, string nombrePartida) {
            base.Channel.EnviarMensaje(mensaje, nombrePartida);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeAsync(string mensaje, string nombrePartida) {
            return base.Channel.EnviarMensajeAsync(mensaje, nombrePartida);
        }
        
        public void EnviarMensajePartida(string mensaje, string nombrePartida, int tipoMensaje) {
            base.Channel.EnviarMensajePartida(mensaje, nombrePartida, tipoMensaje);
        }
        
        public System.Threading.Tasks.Task EnviarMensajePartidaAsync(string mensaje, string nombrePartida, int tipoMensaje) {
            return base.Channel.EnviarMensajePartidaAsync(mensaje, nombrePartida, tipoMensaje);
        }
        
        public void SalirChat(string nombrePartida) {
            base.Channel.SalirChat(nombrePartida);
        }
        
        public System.Threading.Tasks.Task SalirChatAsync(string nombrePartida) {
            return base.Channel.SalirChatAsync(nombrePartida);
        }
        
        public void SalirChatPartida(string nombrePartida) {
            base.Channel.SalirChatPartida(nombrePartida);
        }
        
        public System.Threading.Tasks.Task SalirChatPartidaAsync(string nombrePartida) {
            return base.Channel.SalirChatPartidaAsync(nombrePartida);
        }
    }
}
