//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casilla
    {
        public int IdCasilla { get; set; }
        public short numero { get; set; }
        public short movimiento { get; set; }
        public bool bonus { get; set; }
    
        public virtual Tablero Tablero { get; set; }
    }
}
