//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadisticas
    {
        public int IdEstadisticas { get; set; }
        public short puntos { get; set; }
        public short victorias { get; set; }
    
        public virtual Jugador Jugador { get; set; }
    }
}
