//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        public int IdJugador { get; set; }
        public string nombreUsuario { get; set; }
        public string contrasenia { get; set; }
        public string correoElectronico { get; set; }
        public short puntos { get; set; }
        public short victorias { get; set; }
        public string codigo { get; set; }
        public bool validado { get; set; }
    
        public virtual Tiro Tiro { get; set; }
        public virtual Partida Partida { get; set; }
    }
}
